name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.1.0)'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Update version in pyproject.toml
        run: |
          sed -i 's/version = "[^"]*"/version = "${{ github.event.inputs.version }}"/' pyproject.toml

      - name: Update version in uv.lock
        run: uv lock

      - name: Commit version update
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: bump version to ${{ github.event.inputs.version }}'
          file_pattern: 'pyproject.toml uv.lock'

  create-tag-and-release:
    runs-on: ubuntu-latest
    needs: update-version
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull latest changes
        run: git pull origin ${{ github.ref_name }}
      - name: Create tag
        run: |
          git tag v${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: |
            ## What's Changed

            ## New Contributors

            **Full Changelog**: ${{ github.server_url }}/${{ github.repository }}/compare/v${{ github.event.inputs.version }}-${{ github.event.inputs.version }}
          draft: false
          prerelease: false

  publish-docker:
    name: Publish Docker image
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: create-tag-and-release
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull latest changes
        run: git pull origin ${{ github.ref_name }}
      - name: Fetch tags
        run: git fetch --tags --force

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=v${{ github.event.inputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=v${{ github.event.inputs.version }}
            type=semver,pattern={{major}},value=v${{ github.event.inputs.version }}
            type=sha
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
